name: Echo on Push to Main

on:
  push:
    branches:
      - main

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Push detected on main branch!"
